### ISSUE TITLE
how to be in a garage

### ISSUE THREAD

**Issue by SEAPUNK** [jamen/knowledge#1]
how to buy lamborghini???

**Comment by jamen** [comment]
1. code another MVVM framework
 2. get github stars
 3. ????
 4. profit

**Comment by SEAPUNK** [comment]
wtf where's the step where you buy bookshelves

**Comment by jamen** [comment]
Oh shit, 2 days later and I finally got the joke.

Lmao.

**Comment by SEAPUNK** [comment]
took you long enough
